from django.contrib.auth import views as auth_views
from django.urls import path
from hirewise import views, recruitment, interviews, payments, operations
from hirewise.accounts import QueuedPasswordResetView

urlpatterns = [
    path('pricing/', payments.pricing, name='pricing'),
    path('portal/billing/', payments.billing, name='billing'),
    path('portal/checkout/<uuid:pk>/', payments.checkout, name='checkout'),
    path('portal/payments/<uuid:pk>/', payments.payment_detail, name='payment_detail'),
    path('portal/payments/<uuid:pk>/simulate/', payments.simulate_payment, name='simulate_payment'),
    path('portal/invoices/<uuid:pk>/', payments.invoice, name='invoice'),
    path('integrations/sandbox/webhook/', payments.sandbox_webhook, name='sandbox_webhook'),
    path('applications/<uuid:pk>/rescreen/', operations.rescreen, name='rescreen'),
    path('applications/<uuid:pk>/report/', operations.candidate_report, name='candidate_report'),
    path('applications/<uuid:pk>/interview/', interviews.interview_create, name='interview_create'),
    path('interviews/<uuid:pk>/', interviews.interview_detail, name='interview_detail'),
    path('interviews/<uuid:pk>/assess/', interviews.assess_interview, name='assess_interview'),
    path('portal/company/<uuid:pk>/slots/', interviews.slot_create, name='slot_create'),
    path('portal/company/<uuid:pk>/invite/', operations.invite_team, name='invite_team'),
    path('portal/team/accept/<str:token>/', operations.accept_team, name='accept_team'),
    path('portal/analytics/', operations.analytics, name='analytics'),
    path('portal/export/summary/', operations.export_csv, name='export_csv'),
    path('portal/privacy/export/', operations.own_export, name='own_export'),
    path('portal/admin/configuration/', operations.settings_view, name='platform_settings'),
    path('portal/admin/prices/', operations.prices, name='prices'),
    path('portal/admin/audit/', operations.audit_log, name='audit_log'),
    path('portal/admin/privacy/', operations.privacy_queue, name='privacy_queue'),
    path('applications/recover/', operations.guest_recover, name='guest_recover'),
    path('jobs/', recruitment.jobs, name='jobs'),
    path('jobs/<uuid:pk>/', recruitment.job_detail, name='job_detail'),
    path('jobs/<uuid:pk>/apply/', recruitment.apply, name='apply'),
    path('portal/jobs/', recruitment.recruiter_jobs, name='recruiter_jobs'),
    path('portal/jobs/new/', recruitment.job_edit, name='job_create'),
    path('portal/jobs/<uuid:pk>/', recruitment.job_manage, name='job_manage'),
    path('portal/jobs/<uuid:pk>/edit/', recruitment.job_edit, name='job_edit'),
    path('portal/jobs/<uuid:pk>/action/', recruitment.job_action, name='job_action'),
    path('portal/admin/jobs/', recruitment.moderation, name='moderation'),
    path('applications/', recruitment.applications, name='applications'),
    path('portal/applications/', recruitment.applications),
    path('applications/received/', recruitment.application_received, name='application_received'),
    path('applications/guest/<uuid:pk>/<str:token>/', recruitment.guest_verify, name='guest_verify'),
    path('applications/<uuid:pk>/', recruitment.application_detail, name='application_detail'),
    path('applications/<uuid:pk>/transition/', recruitment.application_transition, name='application_transition'),
    path('documents/<uuid:pk>/', recruitment.document_link, name='document_link'),
    path('documents/download/<str:token>/', recruitment.document_download, name='document_download'),
    path('', views.home, name='home'),
    path('health/', views.health, name='health'),
    path('robots.txt', views.robots),
    path('accounts/register/', views.register, name='register'),
    path('accounts/login/', views.sign_in, name='login'),
    path('accounts/logout/', views.sign_out, name='logout'),
    path('accounts/verification/', views.verification_pending, name='verification_pending'),
    path('accounts/verify/<str:token>/', views.verify_email, name='verify_email'),
    path('accounts/mfa/', views.mfa, name='mfa'),
    path('accounts/password-reset/', QueuedPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('portal/company/new/', views.company_create, name='company_create'),
    path('portal/company/<uuid:pk>/', views.company_detail, name='company_detail'),
    path('portal/admin/company/<uuid:pk>/', views.company_moderate, name='company_moderate'),
    path('portal/profile/', views.profile, name='profile'),
    path('portal/privacy/', views.privacy, name='privacy_centre'),
    path('pages/<slug:page>/', views.info, name='info'),
]
