# Generated by Django 5.2.17 on 2026-09-11 19:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirewise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='Hirewise', max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('legal_entity', models.CharField(blank=True, max_length=200)),
                ('legal_address', models.TextField(blank=True)),
                ('legal_tax_reference', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='QAR', max_length=3)),
                ('retention_days', models.PositiveIntegerField(default=180)),
                ('payments_required', models.BooleanField(default=False)),
                ('interviews_enabled', models.BooleanField(default=True)),
                ('blind_review', models.BooleanField(default=True)),
                ('notice_version', models.CharField(default='development-v1', max_length=40)),
                ('production_intake_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('cover_letter', models.TextField(blank=True, max_length=10000)),
                ('screening_answer', models.TextField(blank=True, max_length=5000)),
                ('profile_url', models.URLField(blank=True)),
                ('stage', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('ai_screening', 'Ai Screening'), ('interview_requested', 'Interview Requested'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('human_review', 'Human Review'), ('shortlisted', 'Shortlisted'), ('employer_interview', 'Employer Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived')], default='received', max_length=30)),
                ('guest_token_hash', models.CharField(blank=True, max_length=64)),
                ('guest_token_expires', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('legal_hold', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('purpose', models.CharField(max_length=100)),
                ('notice_version', models.CharField(max_length=50)),
                ('action', models.CharField(default='accepted', max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirewise.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('storage_key', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=8)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(default='quarantined', max_length=30)),
                ('processing_status', models.CharField(default='pending', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hirewise.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parser_version', models.CharField(max_length=60)),
                ('sections', models.JSONField(default=list)),
                ('confidence', models.CharField(default='unverified', max_length=30)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='hirewise.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=180)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(default='Doha', max_length=120)),
                ('country', models.CharField(default='QA', max_length=2)),
                ('workplace', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='onsite', max_length=12)),
                ('employment', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('seniority', models.CharField(blank=True, max_length=80)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(max_length=20000)),
                ('responsibilities', models.TextField(blank=True, max_length=10000)),
                ('requirements_text', models.TextField(blank=True, max_length=10000)),
                ('preferred_text', models.TextField(blank=True, max_length=10000)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='QAR', max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published'), ('paused', 'Paused'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('interview_enabled', models.BooleanField(default=False)),
                ('screening_question', models.CharField(blank=True, max_length=500)),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hirewise.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hirewise.job'),
        ),
        migrations.CreateModel(
            name='RecruiterNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('text', models.TextField(max_length=5000)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hirewise.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('experience', 'Experience'), ('education', 'Education'), ('certification', 'Certification'), ('language', 'Language'), ('preferred', 'Preferred')], max_length=30)),
                ('mandatory', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='hirewise.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreeningRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('provider', models.CharField(default='local-rules', max_length=60)),
                ('model_version', models.CharField(default='rules-v1', max_length=60)),
                ('prompt_version', models.CharField(default='none-local-rules', max_length=60)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('source_ids', models.JSONField(default=list)),
                ('score', models.PositiveIntegerField(null=True)),
                ('recommendation', models.CharField(default='Review Required', max_length=30)),
                ('evidence', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('input_hash', models.CharField(max_length=64)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='hirewise.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('previous', models.CharField(blank=True, max_length=30)),
                ('current', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True, max_length=2000)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hirewise.application')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('leased_until', models.DateTimeField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirewise.document')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='hirewise_ba_status_50fe21_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='hirewise_jo_company_9dc7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='hirewise_jo_status_25cc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'stage', '-created_at'], name='hirewise_ap_job_id_97c993_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', '-created_at'], name='hirewise_ap_candida_d73d15_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymized_at', None), ('email_verified', True)), fields=('job', 'email'), name='unique_verified_application'),
        ),
    ]
