# Generated by Django 5.2.17 on 2026-09-11 19:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirewise', '0002_platformconfig_application_consent_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('QAR', 'QAR'), ('USD', 'USD')], default='QAR', max_length=3)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('reviewed', 'Human reviewed')], default='invited', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('consented_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('template_version', models.CharField(default='recruiter-text-v1', max_length=60)),
                ('rubric', models.TextField(max_length=5000)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hirewise.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('provider', models.CharField(default='human', max_length=60)),
                ('model_version', models.CharField(default='human-rubric-v1', max_length=60)),
                ('score', models.PositiveIntegerField()),
                ('explanation', models.TextField(max_length=10000)),
                ('evidence', models.JSONField(default=list)),
                ('rubric_snapshot', models.TextField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='hirewise.interview')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=1000)),
                ('position', models.PositiveIntegerField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hirewise.interview')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('text', models.TextField(max_length=10000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='hirewise.interviewquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('item_description', models.CharField(max_length=200)),
                ('provider', models.CharField(default='internal-sandbox', max_length=40)),
                ('provider_reference', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('sandbox', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hirewise.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hirewise.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hirewise.price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('number', models.CharField(max_length=100, unique=True)),
                ('legal_snapshot', models.JSONField(default=dict)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hirewise.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('sandbox', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hirewise.job')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hirewise.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hirewise.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirewise.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirewise.company')),
                ('interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='hirewise.interview')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'starts_at'), name='unique_company_interview_slot')],
            },
        ),
    ]
